### ISSUE TITLE
New call flow is not creating Cases via VMX2, old flows still are

### ISSUE THREAD

**Issue by appledina** [amazon-connect/amazon-connect-salesforce-scv#165]
We created a new inbound call flow for a new phone number/queue that points to the same VMX2 flow for voicemail as our original call flows. The very first voicemail I tested on the new flow created a Case as expected, but every test since then is attaching the voicemail recording to the Voice Call record (SF's native solution). No changes were made to any call flows between tests and voicemails going through the original call flow are still creating cases.

While we intend to migrate to the native solution at some point it's further down our roadmap and we are just trying to get a quick turnaround on this new flow.

**Comment by dougjaso** [comment]
You will need to disable Salesforce’s trigger on the kinesis streams for CTRs that executes their lambda for the start of the voicemail process.. Since Salesforce cloned this solution, the two are competing and the first one to get the record and get to transcription will effectively block the other.

Go to your VoiceMailAudioProcessingFunction provided by Salesforce, and remove the kinesis trigger. When you are ready to switch to their solution, re-add the trigger and remove it from the KVStoS3 funciton that came with Voicemail express


-----------
Jason Douglas
Principal Solutions Architect
Amazon Connect

704.807.6561 – mobile
415.262.9741 – office

[signature_2001959500]<http://www.aws.amazon.com/>

Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=dougjaso&fn=Jason&ln=Douglas>.


From: appledina ***@***.***>
Reply-To: amazon-connect/amazon-connect-salesforce-scv ***@***.***>
Date: Friday, December 15, 2023 at 8:55 AM
To: amazon-connect/amazon-connect-salesforce-scv ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amazon-connect/amazon-connect-salesforce-scv] New call flow is not creating Cases via VMX2, old flows still are (Issue #165)


We created a new inbound call flow for a new phone number/queue that points to the same VMX2 flow for voicemail as our original call flows. The very first voicemail I tested on the new flow created a Case as expected, but every test since then is attaching the voicemail recording to the Voice Call record (SF's native solution). No changes were made to any call flows between tests and voicemails going through the original call flow are still creating cases.

While we intend to migrate to the native solution at some point it's further down our roadmap and we are just trying to get a quick turnaround on this new flow.

**Comment by appledina** [comment]
Thanks! Is the VoiceMailAudioProcessingFunction found in a specific AWS service in the console? Having trouble locating it.

**Comment by dougjaso** [comment]
It is an AWS lambda function.

Sent from my iPhone

On Dec 15, 2023, at 9:34 AM, appledina ***@***.***> wrote:

﻿

Thanks! Is the VoiceMailAudioProcessingFunction found in a specific AWS service in the console? Having trouble locating it.

**Comment by appledina** [comment]
Found it, thank you.

**Comment by appledina** [comment]
Perfect, that worked. Thanks as always, Jason!
