### ISSUE TITLE
"Record 1 Failed to change vm_flag" after creating case for voicemail

### ISSUE THREAD

**Issue by amit-gayal** [amazon-connect/amazon-connect-salesforce-scv#26]
The packager code fails to update the "vm_flag" contact attribute on the voicemail call record. It throws below error:

**Record 1 Failed to change vm_flag**

See attached screenshots:

<img width="746" alt="Screenshot 2020-10-22 at 5 57 23 PM" src="https://user-images.githubusercontent.com/45413902/96871891-80949780-1490-11eb-9836-68b3758b1eb6.png">

**Fix: connect_client = connect_client = boto3.client('connect')**

**Comment by amit-gayal** [comment]
@dougjaso see this

**Comment by dougjaso** [comment]
Does your version have the connect_client updated to be outside of the try/except on line 102? Just trying to make sure. If not, that means I need to fix the version in S3 that is used to deploy, because you should not be seeing that error.

**Comment by amit-gayal** [comment]
No. It's not updated outside try-catch.

**Comment by dougjaso** [comment]
OK. We're going to change how these dpeloyments are automated to address this. Should be done this week. In the meantime, if you copy the code in awsscv_vmx_packager.py and replace the existing lambda code with it, it should solve the issue. The problem is that the zip file wasn't update with the new version of the code, and the zip is what cloudformation uses during deployment.

**Comment by amit-gayal** [comment]
Please let me know when the updates are rolled out.
