### ISSUE TITLE
We want atleast 30 days of Retention Period for Voice mails messages in S3 Bucket.

### ISSUE THREAD

**Issue by magg99** [amazon-connect/amazon-connect-salesforce-scv#69]
We want atleast 30 days of Retention Period for Voice mails messages in S3 Bucket. So, please let me know if there is any way to make this happen.

**Comment by dcarbonetti** [comment]
This isnt really an issue but more of a feature request.

You can extend the life of the file in the s3 bucket, and then have an AWS user manually find and retrieve the recording because the presigned url link will expire after 7 days (see https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/)

other options which i have no clue how to do would be to regenerate the url after 6 days and update the case, or to download the file and store it onto salesforce (may want to watch your data storage)

**Comment by dougjaso** [comment]
You can set the retention for as long as you'd like, the issue here is that the presigned URL that allows you to play the recording directly from Salesforce has a maximum life of 7 days. As commented above, you would then simply need to find and play the file manually from S3.

**Comment by dougjaso** [comment]
Will add the feature request to the list for future consideration

**Comment by magg99** [comment]
Hey Jason.Thanks for writing back. Your Answers have cleared my doubts. Can you suggest any way to extend the life of that Presigned URL so that we can access those Recordings directly from Salesforce even after 7 days of Creation?

**Comment by dougjaso** [comment]
Presigned URLs have a hard limit of 7 days max. [This document](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) explains in detail. Given the limited service list in SCV, i'm looking at either 1. setting up a process to check and update the presigned URL for voicemails every X days until the retention period is hit 2. set up a process to generate the presigned URL on demand or 3. attach the recording directly in Salesforce. #3 is least optimal as it then occupies storage space in SF. This setting, whichever way we do it, will be optional.
